version: "3.4"
services:
  api:
    environment:
      DB_URL: postgresql://user:pass@db:5432/feedback
    build: ./back-end/
    command: -w 4 -b 0.0.0.0:8000
    ports:
      - 5000:8000
  ui:
    build:
      context: ./front-end/
      args:
        REACT_APP_API_URL: /api
    ports:
      - 8081:80
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: feedback
